Repository Almas-Ali/Hacktoberfest_Pattern_Making, pull requests merged in 2022-10, with the labels that each got.

#227 Hollow Triangle Star.cpp
  C++/Hollow Triangle Star.cpp
Labels: hacktoberfest-accepted

#225 Create hollow sqaure patterns
  Python/hollow sqaure patterns
Labels: hacktoberfest-accepted

#236 C program to Convert Upper case to Lower case
  C/Uppercase_to_lowercase.c
Labels: hacktoberfest-accepted

#240 Book Allocation Problem
  C++/bookAllocationProblem.cpp
Labels: hacktoberfest-accepted

#245 username : sdhanraj300 Added bubble sort
  C++/bubbleSort.cpp
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#210 Cyclic_Sort
  C++/Cyclic_Sort
Labels: hacktoberfest-accepted

#247 Added Character pattern code in Python
  Python/Character_Pattern.py
Labels: hacktoberfest-accepted

#246 Create Mirrored-Right-Triangle-Star-Pattern.c
  C/Mirrored-Right-Triangle-Star-Pattern.c
Labels: hacktoberfest-accepted

#238 created count-of-smaller-numbers-after-self
  C++/count-of-smaller-numbers-after-self
Labels: hacktoberfest-accepted

#223 Create All_number_theory_codes.cpp
  C++/All_number_theory_codes.cpp
Labels: hacktoberfest-accepted

#239 Create pattern-N.cpp
  C++/pattern-N.cpp
Labels: hacktoberfest-accepted

#241 swapwihtoudthirdvariable
  C++/swapwithoutthird.cpp
Labels: hacktoberfest-accepted

#250 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#249 TravellingSalseman.cpp
  C++/TravellingSalseman.cpp
Labels: hacktoberfest-accepted

#242 Radix_Sort.c
  C/Radix_Sort.c
Labels: hacktoberfest-accepted

#307 Add C# Diamond Pattern
  C#/DiamondPattern/DiamondPattern.csproj
  C#/DiamondPattern/Program.cs
  C#/DiamondPattern/bin/Debug/net6.0/DiamondPattern.deps.json
  C#/DiamondPattern/bin/Debug/net6.0/DiamondPattern.dll
  C#/DiamondPattern/bin/Debug/net6.0/DiamondPattern.exe
  C#/DiamondPattern/bin/Debug/net6.0/DiamondPattern.pdb
  C#/DiamondPattern/bin/Debug/net6.0/DiamondPattern.runtimeconfig.json
  C#/DiamondPattern/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.AssemblyInfo.cs
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.AssemblyInfoInputs.cache
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.GeneratedMSBuildEditorConfig.editorconfig
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.GlobalUsings.g.cs
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.assets.cache
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.csproj.AssemblyReference.cache
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.csproj.CoreCompileInputs.cache
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.csproj.FileListAbsolute.txt
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.dll
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.genruntimeconfig.cache
  C#/DiamondPattern/obj/Debug/net6.0/DiamondPattern.pdb
  C#/DiamondPattern/obj/Debug/net6.0/apphost.exe
  C#/DiamondPattern/obj/Debug/net6.0/ref/DiamondPattern.dll
  C#/DiamondPattern/obj/Debug/net6.0/refint/DiamondPattern.dll
  C#/DiamondPattern/obj/DiamondPattern.csproj.nuget.dgspec.json
  C#/DiamondPattern/obj/DiamondPattern.csproj.nuget.g.props
  C#/DiamondPattern/obj/DiamondPattern.csproj.nuget.g.targets
  C#/DiamondPattern/obj/project.assets.json
  C#/DiamondPattern/obj/project.nuget.cache
Labels: bug, invalid

#306 Add python staircase pattern with recusion
  CONTRIBUTORS.md
  Python/staircase_with_recusion.py
Labels: bug, invalid

#266 Half pyramid pattern
  Python/half_pyramid.py
Labels: bug, invalid

#299 Added Linear Search using Recursion Code
  C++/linear_Search.cpp
Labels: bug, invalid

#295 Triangle pattern - Python
  Python/patternTriangle.py
Labels: bug, invalid

#252 Create LongestCommonSubsequence.java
  Java/LongestCommonSubsequence.java
Labels: bug, invalid

#232 Shubham
  C++/2sum
Labels: bug, invalid

#284 Created Blackjack.py
  Python/blackjack.py
Labels: bug, invalid

#286 Create Pattern.cpp
  C++/Pattern.cpp
Labels: bug, invalid

#260 File Uploaded Jpg to Png Convertor
  Python/Jpg to Png Convertor.py
Labels: bug, invalid

#280 Rhombus Pattern
  C++/Pattern_Question_Rhombus_Pattern.cpp
Labels: bug, invalid

#257 Dy/feat/binary search
  C++/BinarySearch.cpp
  C++/BinarySearch.exe
  C++/linearSearch.cpp
  C++/linearSearch.exe
Labels: bug, invalid

#248 Create Search_a_2D_Matrix.cpp
  C++/Search_a_2D_Matrix.cpp
Labels: bug, invalid

#230 Create Guess the number
  Python/Guess the number
Labels: invalid

#226 Create Heart.java
  Java/Heart.java
Labels: invalid

#205 Hacktober pattern printing
  C++/HacktoberPrinting.cpp
Labels: bug, invalid, question

#208 pallindrom_pattern_triangle.cpp
  C++/pallindrom_pattern_triangle.cpp
Labels: bug, invalid, question

#211 Added swastika pattern
  C++/swastika_pattern.cpp
Labels: bug, invalid

#219 inverted_halfstar_pyramid.cpp
  C++/inverted_halfstar_pyramid.cpp
Labels: bug, invalid

#224 Create flattenDeep.js
  flattenDeep.js
Labels: bug, invalid

#228 Create hourglass.cpp
  C++/hourglass.cpp
Labels: bug, invalid

#233 Create CompanyLogo.py
  Python/CompanyLogo.py
Labels: bug, invalid

#234 Added diamond_pattern program in C folder
  C/diamond_pattern.c
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#235 Added algorithm for matrix rotation
  C++/matrixRotation.cpp
Labels: bug, invalid

#237 floydtriangle , halfpyramid and butterfly pattern
  Java/Pattern Questions/buterfly.java
  Java/Pattern Questions/floydTriangle.java
  Java/Pattern Questions/halfPyramid.java
  Java/Pattern Questions/hollowRectangle.java
  Java/Pattern Questions/inverted.java
Labels: hacktoberfest-accepted

#278 created butterfly pattern in python
  Python/Butterfly.py
Labels: hacktoberfest-accepted

#256 Added Square Number Pattern
  C/Square Number Pattern.c
Labels: bug, invalid

#291 guessing game added
  Python/number game.py
Labels: bug, invalid

#332 Binary Search Tree operations and traversal added
  Java/Tree/BinarySearchTree.java
Labels: bug, invalid

#363 Create bar graph using python turtle
  C++/Pattern.cpp
  Python/Bar Graph/README.md
  Python/Bar Graph/bar_graph.py
Labels: hacktoberfest-accepted

#361 Adicionando um script para calcular fatoriais
  Javascript/fatorialCalc.js
Labels: hacktoberfest-accepted

#360 Alphabet rangoli pattern
  Python/Alphabetrangoli.py
  Python/Search_for_hex_code.py
Labels: hacktoberfest-accepted

#356 Added Facade Javascript Pattern
  Javascript/Facade.js
Labels: hacktoberfest-accepted

#359 Added Hollow Butterfly Pattern
  C/hollowButterflyPattern.c
Labels: hacktoberfest-accepted

#253 added fibonacci pattern generator
  Javascript/fibonacci.js
Labels: hacktoberfest-accepted

#254 python: Add a Pokemon game
  CONTRIBUTORS.md
  Python/pokemon.py
Labels: hacktoberfest-accepted

#385 Triangle Quest Proram add
  Python/permutations.py
  Python/triangle_quest.py
Labels: hacktoberfest-accepted

#267 added a pattern
  Javascript/rightPascaltriangle.js
Labels: question

#302 Create Kth smallest element in BST
  Java/Kth smallest element in BST.java
  Java/Merge two sorted LinkedList.java
Labels: question

#308 Added jospehus problem
  Java/Recursion/josephusproblem.java
Labels: question

#297 butterfly pattern added
  Java/Pattern Questions/butterfly.java
Labels: hacktoberfest-accepted

#301 added codeforces solutions to CPP
  C++/CodeForces Solutions/AhAb AnD gCd.cpp
  C++/CodeForces Solutions/Heist.cpp
  C++/CodeForces Solutions/Sereja and Dima.cpp
  C++/CodeForces Solutions/buy_a_shovel.cpp
  C++/CodeForces Solutions/captian flint.cpp
  C++/CodeForces Solutions/check.cpp
  C++/CodeForces Solutions/chosing_teams.cpp
  C++/CodeForces Solutions/divan and a store.cpp
  C++/CodeForces Solutions/lcm problem.cpp
  C++/CodeForces Solutions/most similar words.cpp
  C++/CodeForces Solutions/ordinary_numbers.cpp
  C++/CodeForces Solutions/polycarp_and_coins.cpp
  C++/CodeForces Solutions/readme.md
  C++/CodeForces Solutions/strange function.cpp
  C++/CodeForces Solutions/team composition.cpp
  C++/CodeForces Solutions/team olympiad.cpp
  C++/CodeForces Solutions/the piles of candies.cpp
  C++/CodeForces Solutions/three_doors.cpp
  C++/CodeForces Solutions/two regular polygons.cpp
  C++/CodeForces Solutions/yes_or_yes.cpp
Labels: hacktoberfest-accepted

#323 Create TicTacToe.cpp
  C++/TicTacToe.cpp
Labels: invalid

#455 Right angled triangle pattern in python user input
  patterns/right_triangle.py
Labels: invalid
